# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_character.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "user_character.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14user_character.proto\x12\x05my.v1"\xb0\x01\n\x15GrantCharacterRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63haracter_code\x18\x03 \x01(\t\x12\x16\n\x0e\x63haracter_name\x18\x04 \x01(\t\x12\x16\n\x0e\x63haracter_type\x18\x05 \x01(\t\x12\x18\n\x10\x63haracter_dialog\x18\x06 \x01(\t\x12\x0e\n\x06source\x18\x07 \x01(\t"Q\n\x16GrantCharacterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\ralready_owned\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2g\n\x14UserCharacterService\x12O\n\x0eGrantCharacter\x12\x1c.my.v1.GrantCharacterRequest\x1a\x1d.my.v1.GrantCharacterResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_character_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GRANTCHARACTERREQUEST"]._serialized_start = 32
    _globals["_GRANTCHARACTERREQUEST"]._serialized_end = 208
    _globals["_GRANTCHARACTERRESPONSE"]._serialized_start = 210
    _globals["_GRANTCHARACTERRESPONSE"]._serialized_end = 291
    _globals["_USERCHARACTERSERVICE"]._serialized_start = 293
    _globals["_USERCHARACTERSERVICE"]._serialized_end = 396
# @@protoc_insertion_point(module_scope)
