# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from domains.my.proto import user_character_pb2 as user__character__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in user_character_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UserCharacterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrantCharacter = channel.unary_unary(
            "/my.v1.UserCharacterService/GrantCharacter",
            request_serializer=user__character__pb2.GrantCharacterRequest.SerializeToString,
            response_deserializer=user__character__pb2.GrantCharacterResponse.FromString,
            _registered_method=True,
        )


class UserCharacterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GrantCharacter(self, request, context):
        """캐릭터 지급 (character 도메인에서 호출)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserCharacterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GrantCharacter": grpc.unary_unary_rpc_method_handler(
            servicer.GrantCharacter,
            request_deserializer=user__character__pb2.GrantCharacterRequest.FromString,
            response_serializer=user__character__pb2.GrantCharacterResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "my.v1.UserCharacterService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("my.v1.UserCharacterService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UserCharacterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GrantCharacter(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/my.v1.UserCharacterService/GrantCharacter",
            user__character__pb2.GrantCharacterRequest.SerializeToString,
            user__character__pb2.GrantCharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
