# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: domains/scan/proto/character.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "domains/scan/proto/character.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"domains/scan/proto/character.proto\x12\x0c\x63haracter.v1"x\n\x15\x43lassificationSummary\x12\x16\n\x0emajor_category\x18\x01 \x01(\t\x12\x17\n\x0fmiddle_category\x18\x02 \x01(\t\x12\x1b\n\x0eminor_category\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_minor_category"\xd7\x01\n\rRewardRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12;\n\x0e\x63lassification\x18\x04 \x01(\x0b\x32#.character.v1.ClassificationSummary\x12\x16\n\x0esituation_tags\x18\x05 \x03(\t\x12\x1e\n\x16\x64isposal_rules_present\x18\x06 \x01(\x08\x12\x1f\n\x17insufficiencies_present\x18\x07 \x01(\x08"\xed\x01\n\x0eRewardResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x15\n\ralready_owned\x18\x02 \x01(\x08\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x64ialog\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0cmatch_reason\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0e\x63haracter_type\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04type\x18\x07 \x01(\tH\x04\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_dialogB\x0f\n\r_match_reasonB\x11\n\x0f_character_typeB\x07\n\x05_type2e\n\x10\x43haracterService\x12Q\n\x12GetCharacterReward\x12\x1b.character.v1.RewardRequest\x1a\x1c.character.v1.RewardResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "domains.scan.proto.character_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLASSIFICATIONSUMMARY"]._serialized_start = 52
    _globals["_CLASSIFICATIONSUMMARY"]._serialized_end = 172
    _globals["_REWARDREQUEST"]._serialized_start = 175
    _globals["_REWARDREQUEST"]._serialized_end = 390
    _globals["_REWARDRESPONSE"]._serialized_start = 393
    _globals["_REWARDRESPONSE"]._serialized_end = 630
    _globals["_CHARACTERSERVICE"]._serialized_start = 632
    _globals["_CHARACTERSERVICE"]._serialized_end = 733
# @@protoc_insertion_point(module_scope)
