# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x0blocation.v1\"\x8a\x01\n\x13SearchNearbyRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x0e\n\x06radius\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x16\n\x0estore_category\x18\x05 \x01(\t\x12\x17\n\x0fpickup_category\x18\x06 \x01(\t\"X\n\x14SearchNearbyResponse\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.location.v1.LocationEntry\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\xe3\x01\n\rLocationEntry\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0croad_address\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x13\n\x0b\x64istance_km\x18\x06 \x01(\x01\x12\x15\n\rdistance_text\x18\x07 \x01(\t\x12\x16\n\x0estore_category\x18\x08 \x01(\t\x12\x19\n\x11pickup_categories\x18\t \x03(\t\x12\x0f\n\x07is_open\x18\n \x01(\x08\x12\r\n\x05phone\x18\x0b \x01(\t2h\n\x0fLocationService\x12U\n\x0cSearchNearby\x12 .location.v1.SearchNearbyRequest\x1a!.location.v1.SearchNearbyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHNEARBYREQUEST']._serialized_start=32
  _globals['_SEARCHNEARBYREQUEST']._serialized_end=170
  _globals['_SEARCHNEARBYRESPONSE']._serialized_start=172
  _globals['_SEARCHNEARBYRESPONSE']._serialized_end=260
  _globals['_LOCATIONENTRY']._serialized_start=263
  _globals['_LOCATIONENTRY']._serialized_end=490
  _globals['_LOCATIONSERVICE']._serialized_start=492
  _globals['_LOCATIONSERVICE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
