# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x08image.v1\"\xd3\x01\n\x12UploadBytesRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x13\n\x0buploader_id\x18\x04 \x01(\t\x12<\n\x08metadata\x18\x05 \x03(\x0b\x32*.image.v1.UploadBytesRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x13UploadBytesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63\x64n_url\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\\\n\x0cImageService\x12L\n\x0bUploadBytes\x12\x1c.image.v1.UploadBytesRequest\x1a\x1d.image.v1.UploadBytesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADBYTESREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_UPLOADBYTESREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UPLOADBYTESREQUEST']._serialized_start=26
  _globals['_UPLOADBYTESREQUEST']._serialized_end=237
  _globals['_UPLOADBYTESREQUEST_METADATAENTRY']._serialized_start=190
  _globals['_UPLOADBYTESREQUEST_METADATAENTRY']._serialized_end=237
  _globals['_UPLOADBYTESRESPONSE']._serialized_start=239
  _globals['_UPLOADBYTESRESPONSE']._serialized_end=322
  _globals['_IMAGESERVICE']._serialized_start=324
  _globals['_IMAGESERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
